// Covers the render/compare dispatch itself: the drift check has to catch real
// changes, tolerate line-ending noise, and refuse anything it doesn't
// understand rather than passing it silently.
import assert from "node:assert/strict";
import test from "node:test";
import { ASSET_KINDS, compareAsset, renderAsset } from "../src/assets.mjs";
import { tileStandard } from "../src/svg/mark.mjs";

const svgAsset = { path: "test.svg", kind: "svg", svg: () => "<svg/>" };
const pngAsset = { path: "test.png", kind: "png", size: 32, svg: tileStandard };

test("every declared kind can both render and compare", () => {
  assert.deepEqual(ASSET_KINDS, ["svg", "png", "ico", "icns"]);
});

test("renderAsset rejects an unknown kind and names the asset", () => {
  assert.throws(
    () => renderAsset({ path: "mystery.webp", kind: "webp" }),
    /unknown asset kind "webp" for mystery\.webp/,
  );
});

test("compareAsset rejects an unknown kind", () => {
  assert.throws(() => compareAsset("webp", Buffer.alloc(0), Buffer.alloc(0)), /unknown asset kind/);
});

test("svg render carries the generated-by header and a trailing newline", async () => {
  const out = (await renderAsset(svgAsset)).toString("utf8");
  assert.match(out, /^<!-- Generated by @cadencr\/brand/);
  assert.ok(out.endsWith("</svg>\n") || out.endsWith("<svg/>\n"));
});

test("svg compare ignores CRLF but still catches real edits", async () => {
  const rendered = await renderAsset(svgAsset);
  const crlf = Buffer.from(rendered.toString("utf8").replace(/\n/g, "\r\n"));
  assert.equal(await compareAsset("svg", rendered, crlf), null);

  const edited = Buffer.from(rendered.toString("utf8").replace("<svg/>", '<svg r="9"/>'));
  assert.equal(await compareAsset("svg", rendered, edited), "contents differ");
});

test("png compare catches differing pixels and differing dimensions", async () => {
  const at32 = await renderAsset(pngAsset);
  assert.equal(await compareAsset("png", at32, at32), null);

  const at64 = await renderAsset({ ...pngAsset, size: 64 });
  const reason = await compareAsset("png", at32, at64);
  assert.match(reason, /expected 32x32.*found 64x64/);
});

test("identical rasters are rendered once and reused", async () => {
  // Same markup, size, and opacity across two manifest entries — the ICNS
  // retina pairs and the duplicate apple-touch-icon rely on this.
  const a = await renderAsset({ ...pngAsset, path: "one.png" });
  const b = await renderAsset({ ...pngAsset, path: "two.png" });
  assert.equal(a, b, "expected the cached buffer to be reused, not re-rendered");

  const opaque = await renderAsset({ ...pngAsset, path: "three.png", opaque: true });
  assert.notEqual(opaque, a, "opacity must be part of the cache key");
});
