import cadencrMarkDark from "../../../assets/cadencr-mark-dark.svg";
import cadencrMarkLight from "../../../assets/cadencr-mark-light.svg";
import type { ThemeLogo, ThemeLogoVariant } from "./types";

/**
 * The "Index Dots" brand mark (root DESIGN.md "Brand identity"): twelve ink
 * dots on a ring around a solid emerald core. `dark` = ink dots + emerald core
 * for dark grounds; `light` = graphite dots + emerald-deep core for light
 * grounds. Both assets are generated by @cadencr/brand — edit the mark there
 * and run `pnpm brand:install`, never these SVGs by hand.
 */
const CADENCR_ASSET_DISPLAY_SCALE = 1.1;

export const CADENCR_THEME_LOGOS: Record<ThemeLogoVariant, ThemeLogo> = {
  dark: {
    src: cadencrMarkDark,
    alt: "Cadencr",
    variant: "dark",
    displayScale: CADENCR_ASSET_DISPLAY_SCALE,
  },
  light: {
    src: cadencrMarkLight,
    alt: "Cadencr",
    variant: "light",
    displayScale: CADENCR_ASSET_DISPLAY_SCALE,
  },
};
