// Regenerates the raster icon set from the Index Dots mark (DESIGN.md "Logo").
// Standard cut (dots r1.9, core r5.5) for ≥48px; favicon cut (r3 / r7) for ≤32px.
// Run from repo root: node packages/landing/scripts/generate-icons.mjs
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import sharp from "sharp";
import { ringDots } from "../src/lib/logo-dots.mjs";

const PUB = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "public");

const MIDNIGHT = "#0f0f13";
const INK = "#f1f0f4";
const IRIS = "#7c68c9";

// Baked mark for rasters + the served favicon: midnight ground, ink dots,
// iris core (the themeable on-screen version lives in LogoMark.astro).
function mark({ dotR, coreR }) {
  const dots = ringDots()
    .map((d) => `<circle cx="${d.cx}" cy="${d.cy}" r="${dotR}"/>`)
    .join("");
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48">
  <rect width="48" height="48" fill="${MIDNIGHT}"/>
  <g fill="${INK}">${dots}</g>
  <circle cx="24" cy="24" r="${coreR}" fill="${IRIS}"/>
</svg>`;
}

const standardSvg = mark({ dotR: 1.9, coreR: 5.5 });
const faviconSvg = mark({ dotR: 3, coreR: 7 });
const standard = Buffer.from(standardSvg);
const favicon = Buffer.from(faviconSvg);

const png = (svg, size) => sharp(svg, { density: 300 }).resize(size, size).png().toBuffer();

// ICO container with PNG-compressed entries (supported by all modern parsers).
function ico(entries) {
  const header = Buffer.alloc(6);
  header.writeUInt16LE(1, 2); // type: icon
  header.writeUInt16LE(entries.length, 4);
  let offset = 6 + 16 * entries.length;
  const dirs = entries.map(({ size, buf }) => {
    const d = Buffer.alloc(16);
    d.writeUInt8(size >= 256 ? 0 : size, 0);
    d.writeUInt8(size >= 256 ? 0 : size, 1);
    d.writeUInt16LE(1, 4); // planes
    d.writeUInt16LE(32, 6); // bit depth
    d.writeUInt32LE(buf.length, 8);
    d.writeUInt32LE(offset, 12);
    offset += buf.length;
    return d;
  });
  return Buffer.concat([header, ...dirs, ...entries.map((e) => e.buf)]);
}

const jobs = [
  ["favicon-16x16.png", favicon, 16],
  ["favicon-32x32.png", favicon, 32],
  ["favicon-48x48.png", standard, 48],
  ["favicon-96x96.png", standard, 96],
  ["apple-touch-icon.png", standard, 180],
  ["web-app-manifest-192x192.png", standard, 192],
  ["web-app-manifest-512x512.png", standard, 512],
  ["logo.png", standard, 512],
];
for (const [name, svg, size] of jobs) {
  await writeFile(path.join(PUB, name), await png(svg, size));
  console.log("wrote", name);
}

const icoSizes = await Promise.all(
  [16, 32, 48].map(async (size) => ({ size, buf: await png(size <= 32 ? favicon : standard, size) })),
);
await writeFile(path.join(PUB, "favicon.ico"), ico(icoSizes));
console.log("wrote favicon.ico");

// The served SVG favicon uses the favicon cut — write it from the same source
// so its coordinates can never drift from the rasters above.
await writeFile(
  path.join(PUB, "favicon.svg"),
  `<!-- Generated by scripts/generate-icons.mjs — do not edit by hand. -->\n${faviconSvg}\n`,
);
console.log("wrote favicon.svg");
