// Turning one manifest entry into bytes, and comparing those bytes against
// what is committed. Both live here so the set of asset kinds is declared
// exactly once — a kind that can be rendered but not compared (or vice versa)
// would otherwise only surface when `--check` next ran.
//
// On the comparison rules: PNG bytes are stable across repeated runs on one
// machine, but NOT across a sharp/libvips/zlib-ng bump or between macOS and
// Linux prebuilds, so a byte check would false-fail on CI. librsvg's
// rasterization of a given SVG at a given size is deterministic though, so we
// compare decoded pixels instead. SVGs are text we author, compared as text.
import { ico, readIco } from "./encode/ico.mjs";
import { icns, readIcns } from "./encode/icns.mjs";
import { opaquePng, png, rawPixels } from "./encode/raster.mjs";
import { GROUND } from "./tokens.mjs";

const GENERATED_HEADER =
  "<!-- Generated by @cadencr/brand — run `pnpm brand:install`. Do not edit by hand. -->";

// A full run asks for 36 rasters but only 20 distinct ones: the two
// apple-touch-icon copies are the same image, the ICNS retina pairs repeat a
// physical size under two chunk ids, and the favicon cuts recur across both
// consumer packages. Rasterizing each unique (markup, size, opaque) once cuts
// render time roughly in half and keeps that saving as manifests grow.
const rasterCache = new Map();

function rasterize({ svg, size, opaque }) {
  const markup = svg();
  const key = `${JSON.stringify(size)}|${opaque ? 1 : 0}|${markup}`;
  if (!rasterCache.has(key)) {
    rasterCache.set(key, opaque ? opaquePng(markup, size, GROUND) : png(markup, size));
  }
  return rasterCache.get(key);
}

/** Rasterize every entry of a multi-image container in parallel. */
function rasterizeEntries(entries, field) {
  return Promise.all(entries.map(async (e) => ({ [field]: e[field], buf: await rasterize(e) })));
}

function textDiff(expected, actual) {
  // .gitattributes pins these to LF, but a Windows checkout with a global
  // core.autocrlf can still land CRLF on disk. That is a line-ending
  // difference, not brand drift, so compare as text rather than bytes.
  const normalize = (buf) => buf.toString("utf8").replace(/\r\n/g, "\n");
  return normalize(expected) === normalize(actual) ? null : "contents differ";
}

async function pixelDiff(expected, actual, label) {
  const [a, b] = await Promise.all([rawPixels(expected), rawPixels(actual)]);
  if (a.width !== b.width || a.height !== b.height || a.channels !== b.channels) {
    return `${label}: expected ${a.width}x${a.height}x${a.channels}, found ${b.width}x${b.height}x${b.channels}`;
  }
  return a.data.equals(b.data) ? null : `${label}: pixels differ`;
}

/** Compare a container's entries by an identity key, then pixel-compare each. */
async function containerDiff(expected, actual, key) {
  const want = expected.map((e) => `${e[key]}`);
  const found = actual.map((e) => `${e[key]}`);
  if (want.join(",") !== found.join(",")) {
    return `entries differ: expected [${want.join(", ")}], found [${found.join(", ")}]`;
  }
  const diffs = await Promise.all(
    expected.map((e, i) => pixelDiff(e.buf, actual[i].buf, `entry ${e[key]}`)),
  );
  return diffs.find(Boolean) ?? null;
}

const KINDS = {
  svg: {
    render: (asset) => Buffer.from(`${GENERATED_HEADER}\n${asset.svg()}\n`),
    compare: textDiff,
  },
  png: {
    render: rasterize,
    compare: (expected, actual) => pixelDiff(expected, actual, "image"),
  },
  ico: {
    render: async (asset) => ico(await rasterizeEntries(asset.entries, "size")),
    compare: (expected, actual) => containerDiff(readIco(expected), readIco(actual), "size"),
  },
  icns: {
    render: async (asset) => icns(await rasterizeEntries(asset.entries, "type")),
    compare: (expected, actual) => containerDiff(readIcns(expected), readIcns(actual), "type"),
  },
};

/** The asset kinds a manifest entry may declare. */
export const ASSET_KINDS = Object.keys(KINDS);

function kindOf(kind, where) {
  const entry = KINDS[kind];
  if (!entry) throw new Error(`unknown asset kind "${kind}"${where ? ` for ${where}` : ""}`);
  return entry;
}

/** Render one manifest entry to the bytes that belong on disk. */
export function renderAsset(asset) {
  return kindOf(asset.kind, asset.path).render(asset);
}

/**
 * Compare freshly rendered bytes against what is on disk.
 * Returns a human-readable reason, or null when they match.
 */
export function compareAsset(kind, expected, actual) {
  return kindOf(kind).compare(expected, actual);
}
