#!/usr/bin/env bash
set -euo pipefail

# Ralph loop for: Diff Viewer
# Item: diff-viewer
# Generated by simplan item:ralph
#
# Usage:
#   ./ralph.sh          # Run all remaining phases
#   ./ralph.sh --dry    # Show what would run without executing
#
# Ralph loop best practices (https://ghuntley.com/loop):
# - Fresh context per iteration (new claude process each phase)
# - One phase per loop — small, focused, bisect-safe
# - Progress tracked via plan file, not context window
# - Stops on failure so you can intervene

export SIMPLAN_RALPH=true

ITEM_SLUG="diff-viewer"
PLAN_FILE=".simplan/items/${ITEM_SLUG}/PLAN.md"
ITEM_FILE=".simplan/items/${ITEM_SLUG}/ITEM.md"
DRY_RUN="${1:-}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${BLUE}[ralph]${NC} $*"; }
ok()  { echo -e "${GREEN}[ralph]${NC} $*"; }
err() { echo -e "${RED}[ralph]${NC} $*"; }
warn(){ echo -e "${YELLOW}[ralph]${NC} $*"; }

# Count completed and total phases
count_phases() {
  local total=$(grep -c '^### [⬜🔄✅] Phase' "$PLAN_FILE" || true)
  local done=$(grep -c '^### ✅ Phase' "$PLAN_FILE" || true)
  echo "$done/$total"
}

count_remaining() {
  grep -c '^### [⬜🔄] Phase' "$PLAN_FILE" || echo 0
}

log "Ralph loop for: Diff Viewer"
log "Progress: $(count_phases)"
echo ""

PHASE_NUM=0
while true; do
  REMAINING=$(count_remaining)
  if [ "$REMAINING" -eq 0 ]; then
    ok "All phases complete!"
    break
  fi

  PHASE_NUM=$((PHASE_NUM + 1))
  log "=== Iteration $PHASE_NUM ($REMAINING phases remaining) ==="

  if [ "$DRY_RUN" = "--dry" ]; then
    warn "[dry run] Would execute next phase via claude"
    break
  fi

  # Claude runs interactively — you see everything live.
  # When the phase is done, review the changes then press Ctrl+C to
  # end this Claude session. The loop will start the next phase.
  log "Press Ctrl+C when Claude is done to continue to the next phase."
  claude --allowedTools 'Read,Write,Edit,Bash(git *),Bash(npm *),Bash(npx *),Bash(pnpm *),Glob,Grep,Task' \
    --verbose "/item:exec $ITEM_SLUG" || true

  ok "Iteration $PHASE_NUM complete. Progress: $(count_phases)"
  echo ""

  # Brief pause between iterations (context cooldown)
  sleep 2
done

ok "Ralph loop finished for '$ITEM_SLUG'"
ok "Final progress: $(count_phases)"
