pub(super) const BUILTIN_COMMANDS: &[(&str, &str)] = &[
    (
        "add-dir",
        "Add a working directory for file access during the current session",
    ),
    ("agents", "Manage agent configurations"),
    (
        "autofix-pr",
        "Spawn a Claude Code on the web session that watches the current branch PR",
    ),
    (
        "batch",
        "Orchestrate large-scale changes across a codebase in parallel",
    ),
    ("branch", "Create a branch of the current conversation"),
    (
        "btw",
        "Ask a quick side question without adding to the conversation",
    ),
    ("chrome", "Configure Claude in Chrome settings"),
    ("claude-api", "Load Claude API reference material"),
    ("clear", "Start a new conversation with empty context"),
    ("color", "Set the prompt bar color for the current session"),
    (
        "compact",
        "Free up context by summarizing the conversation so far",
    ),
    ("config", "Open the Settings interface"),
    ("context", "Visualize current context usage"),
    ("copy", "Copy the last assistant response to clipboard"),
    ("cost", "Alias for usage"),
    (
        "debug",
        "Enable debug logging for the current session and troubleshoot issues",
    ),
    (
        "desktop",
        "Continue the current session in the Claude Code Desktop app",
    ),
    ("diff", "Open an interactive diff viewer"),
    (
        "doctor",
        "Diagnose and verify your Claude Code installation and settings",
    ),
    ("effort", "Set the model effort level"),
    ("exit", "Exit the CLI"),
    ("export", "Export the current conversation as plain text"),
    (
        "extra-usage",
        "Configure extra usage to keep working when rate limits are hit",
    ),
    ("fast", "Toggle fast mode"),
    ("feedback", "Submit feedback about Claude Code"),
    (
        "fewer-permission-prompts",
        "Reduce common read-only permission prompts",
    ),
    ("focus", "Toggle the focus view"),
    (
        "heapdump",
        "Write diagnostic heap snapshots for high memory usage",
    ),
    ("help", "Show help and available commands"),
    ("hooks", "View hook configurations for tool events"),
    ("ide", "Manage IDE integrations and show status"),
    ("init", "Initialize project guidance"),
    (
        "insights",
        "Generate a report analyzing your Claude Code sessions",
    ),
    (
        "install-github-app",
        "Set up the Claude GitHub Actions app for a repository",
    ),
    ("install-slack-app", "Install the Claude Slack app"),
    (
        "keybindings",
        "Open or create your keybindings configuration file",
    ),
    ("login", "Sign in to your Anthropic account"),
    ("logout", "Sign out from your Anthropic account"),
    (
        "loop",
        "Run a prompt repeatedly while the session stays open",
    ),
    (
        "mcp",
        "Manage MCP server connections and OAuth authentication",
    ),
    (
        "memory",
        "Edit CLAUDE.md memory files and auto-memory entries",
    ),
    ("mobile", "Show QR code to download the Claude mobile app"),
    ("model", "Select or change the AI model"),
    ("passes", "Share a free week of Claude Code with friends"),
    ("permissions", "Manage tool permission rules"),
    ("plan", "Enter plan mode directly from the prompt"),
    ("plugin", "Manage Claude Code plugins"),
    (
        "powerup",
        "Discover Claude Code features through interactive lessons",
    ),
    ("privacy-settings", "View and update privacy settings"),
    (
        "recap",
        "Generate a one-line summary of the current session",
    ),
    (
        "release-notes",
        "View the changelog in an interactive version picker",
    ),
    ("reload-plugins", "Reload all active plugins"),
    (
        "remote-control",
        "Make this session available for remote control",
    ),
    ("remote-env", "Configure the default remote environment"),
    ("rename", "Rename the current session"),
    ("resume", "Resume a conversation"),
    (
        "review",
        "Review a pull request locally in your current session",
    ),
    (
        "rewind",
        "Rewind the conversation and/or code to a previous point",
    ),
    ("sandbox", "Toggle sandbox mode"),
    ("schedule", "Create, update, list, or run routines"),
    (
        "security-review",
        "Analyze pending changes for security vulnerabilities",
    ),
    ("setup-bedrock", "Configure Amazon Bedrock authentication"),
    ("setup-vertex", "Configure Google Vertex AI authentication"),
    (
        "simplify",
        "Review recently changed files and fix quality issues",
    ),
    ("skills", "List available skills"),
    ("stats", "Alias for usage"),
    ("status", "Open the Settings status interface"),
    ("statusline", "Configure Claude Code status line"),
    ("stickers", "Order Claude Code stickers"),
    ("tasks", "List and manage background tasks"),
    ("team-onboarding", "Generate a team onboarding guide"),
    (
        "teleport",
        "Pull a Claude Code on the web session into this terminal",
    ),
    ("terminal-setup", "Configure terminal keybindings"),
    ("theme", "Change the color theme"),
    ("tui", "Set the terminal UI renderer"),
    ("ultraplan", "Draft a plan in an ultraplan session"),
    ("ultrareview", "Run a deep multi-agent code review"),
    ("upgrade", "Open the upgrade page"),
    (
        "usage",
        "Show session cost, plan usage limits, and activity stats",
    ),
    ("voice", "Toggle voice dictation"),
    (
        "web-setup",
        "Connect your GitHub account to Claude Code on the web",
    ),
];
